### ISSUE TITLE
接口非常好用

### ISSUE THREAD

**Issue by lichanghai** [DengXiangHong/react-native-retu-bugly#1]
就是Bugly后台经常收不到，发了很多次，只收到第一次，过很久才能再收到一次，不知道是插件的问题，还是腾讯那边的问题

**Comment by AciGo** [comment]
@Alan0725 我看配置里面没有 android 的 sdk，不需要集成吗？

**Comment by Aceris9527** [comment]
> @Alan0725我看配置里面没有android的sdk，需要集成吗？

@AciGo  已集成，请看这里 👀  [android/build.gradle](https://github.com/Alan0725/react-native-retu-bugly/blob/f52da171cbfd67be78d64cb9a5bbe94a2b4dfad9/android/build.gradle#L115C1-L120C2?plain=1)

**Comment by Aceris9527** [comment]
> 就是Bugly后台经常收不到，发了很多次，只收到一次，过了很久才能再收到一次，不知道是插件的问题，还是腾讯那边的问题

@lichanghai 数据上报有延迟，非即时
